application: connexus-app-ui
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /jquery-ui-map-3.0-rc
  static_dir: jquery-ui-map-3.0-rc

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: /cors
  static_dir: cors

- url: /test
  static_dir: test

- url: /img
  static_dir: img

- url: /json
  static_dir: json
- url: /.*
  script: connexus.application

libraries:
- name: jinja2
  version: latest